version: '3'

services:
  bot:
    container_name: "heehawbot"
    build: .
  db:
    image: "postgres"
    volumes:
    - dbdata:/var/lib/postgresql/data/
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5416:5432"

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/heehawbot/'